### ISSUE TITLE
Muito bonito

### ISSUE THREAD

**Issue by bigbruno** [app-outlet/app-outlet-backend#41]
Gostei da loja, está nos planos incluir suporte a appstream/packagekit?

**Comment by MessiasLima** [comment]
Olá Bruno. Tudo bem?
Ainda nao esta nos planos adicionar esse suporte.. Mas vou deixar pontuado essa sugestao para quem sabe em futuras releases o adicionarmos. Muito obrigado pela sugestao e pelo elogio
